### ISSUE TITLE
[BUG] Collaboration frontend get empty code string response when getting code from backend

### ISSUE THREAD

**Issue by larrywang0701** [CS3219-AY2425S1/cs3219-ay2425s1-project-g36#117]
# Steps to reproduce:
 - This is a bug that sometimes happens and sometimes not, if it's not happening, repeat the steps and try more few times
 - Enter collaboration page after a successful matching
 - Type something into the code editor
 - Open browser's console
 - Click "Practise an Interview" at the page header of the collaboration page
 - The bug happens when the code in the editor lost and the console shows a `code: `

# Behaviors:
## Sometimes the bug happens...
![image](https://github.com/user-attachments/assets/782bbe7c-e79a-4a84-96e1-412b823aae05)
(also `matchedUser` is null, maybe another bug from the backend)
## Sometimes it works without the bug...
![image](https://github.com/user-attachments/assets/cf255bdf-9604-4af8-9f71-af0e3f68d53e)
 
# To clarify why I think the bug of empty code editor may comes from the collaboration backend:
![image](https://github.com/user-attachments/assets/dc1ac36b-2d3f-470c-b761-fdc8984e3f58)
When navigating back/reopening collaboration page, for the debug output on **line 106**, sometimes there will be a  `code: ` output at browser's console. Executing the debug output line at 106 means that `load-document` signal from the backend is received by the frontend through WebSocket, but with empty code string in the payload. So I think since the signal itself contains empty code string, and frontend sent the `get-document` signal and received the `load-document` signal successfully, I guess the bug may actually comes from the backend.

**Comment by brein62** [comment]
another bug (since you're fixing bugs here): when you exit out to another page, the content for both the chat and the code window resets as well.

Two ways (but i think they're both the same bug):

First way

Match User A with User B, resulting in collab page
User A clicks on "Practise an Interview"
Text for User A is blank now (code editor + message screen)
Second way

Match User A with User B, resulting in collab page
User A clicks on "PeerPrep" logo on top left
User A goes back to collab page by clicking on "Practise an Interview"
Text for User A is blank now (code editor + message screen)
Functionality improvements:

Add the username above the text for the message feature
Set minimum width of the message window to 300-400px since if you use half the screen width, the message window doesn't look too hot... (doesn't matter that it covers the code editor part)
Set maximum height of the editor + code pane to like 400px (or 100vh - 300px) so that the entire content fits within the page. for any overflows, it should be handled within the two frames, not the page. -> if u can't i can help with this
would still prefer changing the button for language to a dropdown but i can fix it if you dont know how (dont need to stress too much about it)

**Comment by wjayee** [comment]
For zihan's bug, its because of the implementation and isnt really a bug. The save interval was set to 2 seconds which causes the empty code returned since its not saved yet. I'll js lower the interval to 1 second
i think its the same for brendan too

**Comment by brein62** [comment]
it was a different issue entirely but this is still another bug to consider

doesnt take place for me tho
